### ISSUE TITLE
You

### ISSUE THREAD

**Issue by WarpWing** [Nizamovpl/APCSA-Final#1]
You are the issue

**Comment by Nizamovpl** [comment]
<3

**Comment by WarpWing** [comment]
(If Percy's Teacher happens to see this issue, this was made in jest. Percy is a great person. Give him A please xd)

**Comment by Nizamovpl** [comment]
> (If Percy's Teacher happens to see this issue, this was made in jest. Percy is a great person. Give him A please xd)

To add - he asked what code I was doing, and gave me some basic things like which files I should use. If you wanna see the conversation : feel free to ask me.

**Comment by WarpWing** [comment]
save.json > save.csv  *cough*

**Comment by Nizamovpl** [comment]
> save.json > save.csv _cough_

Cough if it works it works, I might change it on a later run
